version: '3.8'
services:
  server:
    build: ./server
    ports:
      - '5000:5000'
    env_file:
      - .env
    volumes:
      - ./server:/usr/src/app
    command: npm run dev
    depends_on:
      - db

  client:
    build: ./client
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    volumes:
      - ./client:/usr/src/app
    command: npm start

  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: text_adventure
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
