version: '3.8'
services:
  server:
    build: ./server
    ports:
      - '5000:5000'
    env_file:
      - .env
    volumes:
      - ./server:/usr/src/app
    command: npm run dev

  client:
    build: ./client
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    volumes:
      - ./client:/usr/src/app
    command: npm start